### ISSUE TITLE
Chiselling any blocks that produce light deactivates them, making them stop producing light.

### ISSUE THREAD

**Issue by SerenDark** [ChiselsAndBits/Chisels-and-Bits#286] opened 2017-07-07 15:16 UTC
* MC Version: 1.11.2
* C&B Version: 13.11
* Do You have Optifine: Yes

A user on my server is having an issue.
"Anything that produces light does not work with the mod. If you chisel glowstone/lamps, it makes them inactive. Is there a way to fix this?"

**Comment by AlgorithmX2** [comment] 2017-07-07 17:40
Glowstone lamps require redstone signal? And C&B doesn't mimic such behaviors, thus a lamp would deactivate when chiseled.

Did I understand your report correctly?

**Comment by eriniki** [comment] 2017-07-10 06:54
I think they mean *all* light-emitting blocks, as I can reproduce it here; Same MC/C&B versions (also OptiFine), chiselling even a single bit out of a Glowstone Block causes it to no longer emit any light at all. 

Haven't done an isolation test (just came across the issue and went to look), but I can do that later also if needed. Screenie attached to show.

![2017-07-10_16 52 29](https://user-images.githubusercontent.com/11290832/28005931-5fd89846-6590-11e7-90e7-f99a752c8031.png)

**Comment by eriniki** [comment] 2017-07-10 09:57
Reproduced it with nothing but C&C and moreoverlays (and I can confirm it isn't moreoverlays, I tested without that first then realised I couldn't see the damn light levels without it, ahaha).

I'm aware the visual lack of fullbright/etc on the first test was just due to OptiFine w/ C&B blocks (and that's fine), but shouldn't chiseled glowstone still emit light? Hope this helps. :3

![2017-07-10_19 52 35](https://user-images.githubusercontent.com/11290832/28012520-62bb3064-65a9-11e7-9cee-feef5ea786b8.png)

**Comment by AlgorithmX2** [comment] 2017-07-11 00:56
This is a duplicate of https://github.com/AlgorithmX2/Chisels-and-Bits/issues/81 I think. If you place glowstone and remove it the situation fixes it self, its sort of an odd issue and I've yet to find a solution yet.

**Comment by AlgorithmX2** [comment] 2017-07-11 01:30
Ok.. I say that, but maybe I figured it out.
if you want to try and confirm, https://www.dropbox.com/s/480k91kbzxfi92x/chiselsandbits-13.11.jar?dl=1

**Comment by eriniki** [comment] 2017-07-11 17:13
I think you've nailed it. 

That same original environment (optifine included, natch) with a single bit chiseled out keeps light perfectly
![2017-07-12_03 07 47](https://user-images.githubusercontent.com/11290832/28080514-a1f2779a-66af-11e7-80f5-4aff37a050ee.png)

And after chiseling it down to a single plane (to approach the 6.25 default on light-emitting) and then knocking bits out of it, it even scales the light level down. 
![2017-07-12_03 08 43](https://user-images.githubusercontent.com/11290832/28080553-c335bd9a-66af-11e7-80a2-35c50b6d7c85.png)

**Comment by eriniki** [comment] 2017-07-12 04:55
Did some more testing (I was dead-tired then, and realised I had solely tested glowstone) - and it seems to work properly with everything I tested; Lamps, Fluids (e.g. lava and TE's energized Glowstone), other light-emitting mod blocks.

**Comment by AlgorithmX2** [comment] 2017-07-12 18:04
Thanks for helping test, This will definitely be in the next official release.

**Comment by eriniki** [comment] 2017-07-18 06:00
Been busy as hell so I spaced out and forgot to reply (oops), but no worries! Was happy to help. Also, is this test build safe to use In The Wild (so to speak)? If so, I'll get it out to the folk on my server (so they can start using glowy bits again) soon, otherwise will wait for the official release. 
By safe also I mostly just mean in the way of regressions elsewhere/excess debug output still in, etc; I don't at all foresee any issues landing on your doorstep from it! :)

Thanks again for hopping on it so swiftly too, actually!

**Comment by AlgorithmX2** [comment] 2017-07-21 03:45
Sorry I didn't respond to this sooner, there is nothing to worry about with using that build. Feel free.

**Closed as completed** 2017-07-22 06:03 UTC
Labels: Duplicate
