### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot set property PropertyEnum

### ISSUE THREAD

**Issue by ElasticKnife** [ChiselsAndBits/Chisels-and-Bits#395] opened 2018-06-09 15:46 UTC
* MC Version: 1.12.2
* C&B Version: 14.17
* Do You have Optifine: Yes

Custom mod pack; unable to replicate without Chisels & Bits; crashes on loading.
Link to crash report: https://paste.dimdev.org/okecetawoc.mccrash

**Comment by AlgorithmX2** [comment] 2018-06-09 18:11
I've seen this crash log before, but someone removed a second mod to fix it.

I'm not really sure how its possible, or why. What should be impossible is happening. However I made a build to catch the exception being throw, i'm not sure whats going to happen after you try it however.

https://www.dropbox.com/s/9fvfn4siz3077qt/chiselsandbits-14.18.jar?dl=1

I guess let me know what happens when you try this build, should it crash some other way, or if another mod shows up  in the stack trace, whatever happens.

**Comment by ZombieHDGaming** [comment] 2018-06-10 18:47
@AlgorithmX2 Hey there, sorry about that. The issue arises when VanillaFix and Chisels & Bits are put together when there is more than 4096 blocks/items in the game. We're not sure why this happens when loading the game, but it does when these two are put together. We have our suspicions that it's probably because of what we modify to allow >4096 blocks/items and C&B doesn't like it, but it's a trial and error thing for now.

By the looks of it, C&B behaves fine in our dev environment with the build you posted, besides a few weird things with particles (but it's not that big of a deal), but other than that, your build seemed to work like normal. VF definitely wants to make compatibility our first priority since we do break some stuff with other mods (as you've noticed). If you want, you can drop by our Discord to talk with me and Runemoro or you make an issue on our tracker so we can make C&B and VF buddies under these circumstances and make them fully compatible.

Cheers,
Zombie

**Comment by AlgorithmX2** [comment] 2018-06-11 21:35
@ZombieHDGaming I don't mess with discord, and very very limited time for communication making tickets the simplest means of communication, even if delayed, but I know that so far NotEnoughID's which also extends block limits seems to work fine.

Have you tried one of the normal builds to try and see what the issue is? The build above is just be catching the exception ( not ideal obviously ), but the under lying error seems to indicate that 

minecraft:golden_rail is missing several valid states.
north_south, east_west, ascending_east, ascending_west, ascending_north, ascending_south are full list provided. which seems far from complete, All the turn states appear to be missing.

If you would like to open an issue on your VanillaFix's tracker and link back I'm certainly not against it, I prefer things to be solved where possible.

**Comment by ZombieHDGaming** [comment] 2018-06-11 22:16
@AlgorithmX2 I *think* I might've figured out the issue between C&B and VF, but I'm doing some testing to see since it might be the Block#getStateById which C&B relies on, which seems to have a hardcoded limit on it........no clue why this is only the first mod we've seen to encounter this issue, but hopefully when we fix it, it should fix compatibility (and yes, I will test to make sure it works fine).

**Comment by ZombieHDGaming** [comment] 2018-06-12 17:03
Yep, it seems we have fixed the compatibility between C&B and VF in our last dev build and this issue can be closed. If anything else arises with VanillaFix and Chisels and Bits and that same type of error, feel free to direct them towards us and we'll take a look at it 😃

**Comment by AlgorithmX2** [comment] 2018-06-16 02:07
Thanks for the update, closing.

**Closed as completed by AlgorithmX2** 2018-06-16 02:07 UTC
Labels: Invalid
