### ISSUE TITLE
Chiseled Blocks from Chisel mod randomly appear and disappear

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#160] opened 2016-11-02 20:06 UTC
I'm using a variation of dark oak planks from the Chisel mod to build a staircase in my house. For some reason, the blocks sometimes are invisible. They are still there, but I can't see them and every once in a while when I login, they are there and show just fine. Not sure if this is specific to just blocks from Chisel and/or if it's already a known issue, just thought I'd post about it.

**Comment by Dushess** [comment] 2016-11-02 20:54
1.9? This is some kind of rendering bug. (actually chiseled block reloading from server bug)
Solved in 11.10 it's on MC1.10, you need to update. Or this bug ANYWAY will appears sometimes.

Tested on my 1.9.4 map, that's even worse, now whole chunk(s) can be stuck-in-loading and only map(with client) reloading CAN fix the problem. Of course temporarily. In addition updating chiseled blocks just by putting bit now not loads affected chunk like i did in 1.9 (only removing bit does that)

**Comment by ghost** [comment] 2016-11-02 20:57
solved in 11.10? I am currently on MC 1.10.2 on Chisels and Bits 12.6 (I know there's an update, but there was nothing about this bug in the changelog).

**Comment by Dushess** [comment] 2016-11-02 20:58
Huh, again? Not so good fixed, @AlgorithmX2 ?

**Comment by Dushess** [comment] 2016-11-02 21:01
> (I know there's an update, but there was nothing about this bug in the changelog)

That problem started in 1.9 and continues until 11.10 released (also in 10.19's changelog, but technically nope), i think in your version it starts again.

**Comment by ghost** [comment] 2016-11-02 21:03
Strange... maybe it's a problem with Chisel, rather than Chisels and Bits?

**Comment by Dushess** [comment] 2016-11-02 21:09
I don't go after 1.9.4 yet, don't know about mod changes in 1.10.2

**Comment by Dushess** [comment] 2016-11-02 21:33
@AnZaNaMa
And how works 12.7? ('cause you fix 1 bug and create 3 more :) ), but just some changes can fix other problems generation, just need to watch code, but it's possible.

**Comment by AlgorithmX2** [comment] 2016-11-02 21:36
@AnZaNaMa 

It might be related to chisel, there used to be a bug where chisel blocks were invisible outright, but they made a change later that seems to make it work usually. Please determine if the problem is isolated to Chisel blocks, or if it also applies to vanilla blocks.

**Comment by ghost** [comment] 2016-11-02 21:49
I'm attempting to test, but I can't seem to get any other blocks, even from chisel to disappear. I'm not quite sure what the conditions are that make them appear either. I'll keep testing and let you know if I find anything.

**Comment by Dushess** [comment] 2016-11-02 22:07
Something strange, updated to 1.10.2 and with C&B 12.1 that chunks still stuck, i just enter the map right now, first rendering shows problem. Don't think that it is normal, and even ingame reload will not fix it i mean...
![2016-11-03_00 02 44](https://cloud.githubusercontent.com/assets/15954961/19949290/4490f190-a16a-11e6-93b5-cc211d7e7d4b.png)
Even in 1.9's version 9.21 problem is much lesser and don't breaks game process at all, like that.

Upd: 11.10 does not fixing it on my installation quickly too, maybe changes on me applies so slow (because 10.19 at first few launches was good). Manual chunk reloading not helps, i can use water for that, chunk updates after water disappears. _11.10 is broken on me?_
It's pretty annoying and even unbelievable, because fixed for this version. Seems to #123 continues.
Will check it more and later on 12.7. I'm tired with this bug....

**Comment by AlgorithmX2** [comment] 2016-11-02 22:35
Why do you keep trying old versions?

**Comment by Dushess** [comment] 2016-11-02 22:37
First, i need it for modpack, but this is low important.
Main problem that fixed bug continues on me in 11.10, and in newer 12.1, where he should be history.
And one more question: Why here problem appears, ignore fix and immediately, but on 1.9.4 with no fix it shows after some time spended on the map?

**Comment by AlgorithmX2** [comment] 2016-11-02 22:55
@Dushess Which bug are you experiencing, your picture seems to show an entire chunk missing.

This is not consistent with your previous report.

Please confirm your issue,
1. All Blocks in the chunk, or render chunk are not rendering ( C&B and other blocks )
2. C&B Blocks in a chunk, or render chunk are not rendering.
3. Some C&B Blocks ( randomly ) are not rendering.

Please ONLY report bugs reproduceable with the latest build. Other wise I'm might just be chasing my tail.

**Comment by Dushess** [comment] 2016-11-02 23:08
Right, will check on 12.7, now problem like in #123 - whole chunk not loads only chiseled blocks, collision present (player shaking when walking on), no highlighting(like no blocks completely) updating with load CB-locks back only by **removing** bits from affected blocks, but restores only that block, all chunk can be restored by plasing and removing water flowing (water sourse does that of course), manual reload chunks (from disk?) not fixing bad chunk. That's all.
If problem will be even on 12.7 and will not fade to good conditions (my side), i will notify, tomorrow. Thanks.

**Comment by Dushess** [comment] 2016-11-02 23:24
Yes, additional info, chunks become corrupted right after changind his content. (I add more ceiling "beams" that showed on picture)
Modpack still the same. On all versions problems caused by that specific block content i think, beams have light sourse from bits, idk, render problems like with weeryan17 or content problems. Because before creating beams i has problems with girgers maded from wool. It was with hard clay within block inside affected chunks, under the roof and was confirmed sourse of "missing" blocks. And after 10.19 i now have described kind of problem. Thats why my report is other.
Plus

> solved in 11.10? I am currently on MC 1.10.2 on Chisels and Bits 12.6 (I know there's an update, but **there was nothing about this bug in the changelog**).

I know about last changes and excess bugsearch, but if problem fixed in one build it will not shows again commonly.
I just confused, how it can be and secondary about strange behavior of previous version on my conditions.

Another upd. In minecraftforum thread ig one log, corellated vith some java problems, it can be useful for us?

**Comment by AlgorithmX2** [comment] 2016-11-03 00:13
@Dushess Please keep new discussion and information relevant to the latest provided build ( 12.7 as of now ) and please try to be more concise Its becoming harder to follow what your talking about as you hop between issue threads and refer to previous items.

Here is my present understanding of your issue ( on 12.7 ) all other information is considered "out of date" and is not going to help tracking down issues that are in the current code base.

Based on what you have said, your issue is, or is similar to #123 

The Bug Described in #123 was rare, sometimes reloading the chunks 5 times to reproduce.
It affected single blocks.
The block did not have valid collision data, it caused 'sticking and vibrating'
The bug reproduces when chunks are sent from the server to the client ( on load ).

But you have stated that your bug differs slightly,
The entire chunk is affected. ( But only C&B Blocks )
It reproduces when you edit something.
You can "clean" the issue by editing each block, or you can place water in the chunk.
Reloading the chunks has no affect, it can be done many times and the issue persists.

This to me sounds like a VERY different bug. Please confirm my understand, or please redefine your bug.

Other information that would be helpful, a crash log ( hold F3+C in game )
A way to reproduce the issue possibly with minimal mods, preferentially just C&B, and Vanilla. Possibly a world file that makes testing easier.

**Comment by Dushess** [comment] 2016-11-03 00:19
That's correct, but single block problem was in 9.21, i have whole chunk problem since 10.19 and 11.10, that somehow not fix problem on me, AND even in 12.1 its bugged. I just suspects my-side problems. No crash log, but the same stackoverflow errors, like in log, located [here](http://www.minecraftforum.net/forums/support/modded-client-support/2752918-wrong-chunks-reloading-ingame-chisels-bits-mod?comment=1)

**Comment by AlgorithmX2** [comment] 2016-11-03 00:26
I was asking if you could make a crash log ( By holding F3 + C ) it just crashes the game to make the log.

You are getting https://github.com/AlgorithmX2/Chisels-and-Bits/issues/118#issuecomment-257642053   entities in your log on the latest version? If so its quite likely related.

Another thing you could try is going into the client performance settings page and raise "Dynamic Model Face Count" to some unrealistic number say 999999 and see if that dose something.

**Comment by Dushess** [comment] 2016-11-03 00:44
Here's [map](https://www.dropbox.com/s/xxkryoxxf69em55/LGW-1.9.4.rar?dl=0) (1.9.4 саn be used vor newer versions) + [modpack](https://www.dropbox.com/s/v0vbo5ulhsiibuu/mods1102.zip?dl=0) for 1.10.2, reuploaded
Yees, it spamming me in the log.

**Comment by Dushess** [comment] 2016-11-03 00:48
And cannot be crashed by f3+c, no this combination in debug command list.
plus only  "Max faces fo static render" is present.
It does: lags at first time, then normal, water now updates chunk when creating, will check reloading from afar.
All 2 chunks reloads bugged.

**Comment by Dushess** [comment] 2016-11-03 08:26
Confirm, any new version starting 10.19 (tested since that) have this bug. Caused by specific contents, it's additional ceiling "beams" in hall. That beams mounted south-north between red pillars, you can reproduce it by copying it from east-west lines, then go away on some distance to unload chunks and go back. This continues even on Vanilla + C&B 12.7 only. That's terrible, i'm sad a little.

**Comment by AlgorithmX2** [comment] 2016-11-03 14:52
@Dushess 
Apparently you have to hold F3+C for several seconds, it certainly worked for me, 

I loaded you map with C&B + Vanilla only, 12.7; and then I ran around the room with the red pillars and placed bits and removed the bits, then I drew a line of bits down the length of the room.

I didn't see any problems, please provide detailed instructions for how to cause the issue.

Have you change any settings in forge? or C&B?

Perhaps provide a screenshot of your F3 screen.

**Comment by mezz** [comment] 2016-11-03 16:40
@Dushess you're being absurdly aggravating, please follow Algo's instructions carefully or leave him alone. You are consistently offering unimportant information while ignoring what is requested.

**Comment by ghost** [comment] 2016-11-03 16:41
Not to mention, hijacking my issue post

**Comment by AlgorithmX2** [comment] 2016-11-03 16:42
@AnZaNaMa speaking of which, have you been able to reproduce your issue?

**Comment by ghost** [comment] 2016-11-03 16:44
No, not at all. It's really strange. The original stairs come and go, but
the new ones I made with the same pattern don't disappear. I guess that
means it's not much of a problem then. I would have to guess its some sort
of corruption with my specific world file or something.

**Comment by AlgorithmX2** [comment] 2016-11-03 16:49
Are you seeing anything in your error log when the issue re-produces? 

Its also possible something near the block is causing problems, so whats around it might be more at fault then the block itself. This might explain why making copies of the block doesn't produce the same issue.

If the issue is reproducing with a specific block you could try providing your world / location and I could try looking at it, beyond that I'm not sure. But before we go that route it would probably make sense to make a copy of the world, and load it with only chisel and C&B ( since those are the components of the block ) that way we eliminate any other near by blocks that could be causing issues.

**Comment by ghost** [comment] 2016-11-03 16:52
The only thing near it that might be affecting it is the lights from the
illumination wand from not enough wands. Other than that, it's against a
wall of chiseled basalt. There are no errors or anything and the One Probe
tool tip thingy says they are still chiseled dark oak planks

**Comment by AlgorithmX2** [comment] 2016-11-03 17:26
Alright, well then I guess the best thing to do at this point would be to back up your world and load with just C&B + Chisel, and make sure that the issue has persisted.

If it does you can forward me the world and I can take at look at the blocks in question, other wise there is probably something conflicting ( maybe even something that's not immediately obvious ).

But we'll need to be sure that its either one or the other before moving on, being scientific about it.

**Comment by ghost** [comment] 2016-11-03 17:31
On it

**Comment by Dushess** [comment] 2016-11-03 17:54
Uhm, sorry, i'll pull yourself together. Just trying to give more clues, but poorly.
So, as i caaan probably mark as source of problem is unusual conditions, that include stained glass surfaces not directed east-west, because current longitudinal beams and also perpendicular on the walls (not in hall middle) not causing problem. 
Now step-by-step, how to reproduce bug, i done it today on my work.

After entering on map all is good, exist only longitudinal beams, now i copied one of them with middle mouse button and start to placing all parts from it to create directly similar beam, but perpendicularly.
It looks like that, wherein used free positioning mode.
![2016-11-03_19 48 05](https://cloud.githubusercontent.com/assets/15954961/19978345/11d18098-a210-11e6-8c60-4a53a6b2574d.png)
Also that clay mini-walls behind red pillars previously was made from stained glass and triggers bug from my first report too.

And next the crashlog...
http://pastebin.com/nVpF828C

**Comment by Dushess** [comment] 2016-11-03 18:19
Right now i'll try to remove it and report result.

**Comment by AlgorithmX2** [comment] 2016-11-03 18:22
@Dushess Thanks for the information when I get some time I'll try to use your instructions + world to reproduce the issue and look into the stack trace in the log as well.

**Comment by Dushess** [comment] 2016-11-03 19:03
Perpendicular beams removed, but it not fixed issue immediately. One chunk become normal, but one in corner of hall is not, i found one more. and water did not reload that. (I miss extending red pillars into beams, but that's minor)
Probably caused by this block, however he present at all pier length on this line. But only this chunk here's problematic.
![2016-11-03_20 57 20](https://cloud.githubusercontent.com/assets/15954961/19981043/adaa2818-a219-11e6-8eb2-38b22f199e9b.png)
 On, yes, almost forgot, not any bit restores chiseled block, onlu that he contains. (CB-block of stone with iron  lines can be restored only by named bits. Maybe not in all cases but on picture above is it.)

**Comment by AlgorithmX2** [comment] 2016-11-04 00:29
@Dushess I haven't been able to reproduce the issue, I did as you suggested and copied the beams running one way, and build a beam going the other direction, I did this 3 times, but nothing seemed to go wrong any of the times.

I also was not able reproduce the stacktrace you reported.

Based on the stack trace I came up with an idea however and I tried that here, https://dl.dropboxusercontent.com/u/9117298/cb/anti-builds/chiselsandbits-12.getTileEntitySafely-extra.jar

So you can try and see if that helps, if it does then I could include it in a new build, other wise I guess back to the drawing board about trying to reproduce the issue... CMP or CSP?

**Comment by Dushess** [comment] 2016-11-04 10:23
Singleplayer, and i suspect my Java machine, seems to be right.
BUT, on my work i tried on Win 7 (not XP), where Java8 should work properly at all.
At least i can mark my game workspace, something can break normal mod's working, but other mods has been removed.

**Comment by Dushess** [comment] 2016-11-04 10:32
So, on start is normal, game loads chunks as usual, ingame reloads also good, in addition it happens much faster, w/o freezes. Clean client with C&B only. Now testing mod dependencies.

Conclusion, good work, it definately better, hidden bug is beaten, thanks.

**Comment by AlgorithmX2** [comment] 2016-11-04 15:45
@Dushess are you saying that the build helped? ... or didn't? or that it was java? I'm not really sure what to take from your responses.

**Comment by Dushess** [comment] 2016-11-04 16:35
@AlgorithmX2 All good, i just writing my thoughts in chronological order. Now problem is solved. Maybe this changes can help AnZaNaMa too.

**Comment by AlgorithmX2** [comment] 2016-11-07 20:11
@AnZaNaMa Have you had a chance to check on things?

**Comment by ghost** [comment] 2016-11-12 00:33
Sorry, I completely forgot about this. I just loaded up the world in singleplayer with only Chisels and Bits and Chisel and as far as I can tell, the problem is not persisting.

**Comment by AlgorithmX2** [comment] 2016-11-12 01:27
Odd, Well I guess unless we can track down some other details we are kind of at a dead end. For now I suppose I'll close the issue, if you end up getting any other details or can reproduce it later we can re-open it.

**Closed as completed by AlgorithmX2** 2016-11-12 01:27 UTC
Labels: Unable To Reproduce
