### ISSUE TITLE
Auto-waterlogging bits blocks creates unwanted bits

### ISSUE THREAD

**Issue by Rodg88** [ChiselsAndBits/Chisels-and-Bits#839] opened 2022-01-13 07:31 UTC
Trying to chisel something solid next to a water source, the water floods the block with the bits (maybe when the top level isnt full of solid bits), creating unwanted water bits. It's quite hard to clean up the water bits, you need to pick them up which fills your bits bag (you can't mine the water bits block without spending a minute just mining the block), and trying to place the water bits to make a full block is very laggy.

For simplicity, I'd say just disable auto-waterlogging, and leave it up to the user if they want to make water bits manually.

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: chiselsandbits-1.0.63.jar
* Do You have Optifine: No

**Comment by marchermans** [comment] 2022-01-13 08:37
The problem is that this was a highly requested feature....
I might consider making it an optional feature.

**Comment by Rodg88** [comment] 2022-01-13 09:29
haha, well fair enough. maybe just letting a tool break water bits quickly would help? As it is, it's hard to 'tidy up' afterwards as there isnt a tool that effective against it. *edit* or requiring right clicking a bucket on the block to waterlog, the vanilla way, could work too?

**Comment by marchermans** [comment] 2022-01-13 10:26
> haha, well fair enough. maybe just letting a tool break water bits quickly would help? As it is, it's hard to 'tidy up' afterwards as there isnt a tool that effective against it. _edit_ or requiring right clicking a bucket on the block to waterlog, the vanilla way, could work too?

Sadly this is the vanilla way....
I just implement its interface, you can test it with stairs: Water can flow into them. C&B follows the same logic, if you do not want water to flow into them then that side has to be completely filled with bits. I might consider allowing you to click them with a sponge to void all fluid bits inside them....

**Comment by Rodg88** [comment] 2022-01-13 10:28
I see, unfortunate. The sponge idea could be handy. I just spilled some water next to my fish tank with a thin bits housing, and it soaked up the flowing water lol
![unknown](https://user-images.githubusercontent.com/2611674/149313091-db9fd743-0435-4bb3-84d7-0a99408442c7.png)

**Comment by marchermans** [comment] 2022-01-16 19:31
Fixed in latest, right click with a sponge

**Closed as completed by marchermans** 2022-01-16 19:31 UTC
Labels: Enhancement, Priority: Low

**Comment by SAOMDVN** [comment] 2026-08-01 04:24
> Sadly this is the vanilla way....
> I just implement its interface, you can test it with stairs: Water can flow into them

Is this still true/Was this true before? I tested this in vanilla by putting a water source block next to a stair block and water doesn't flow into them. Unless I misunderstood the meaning of your sentence...
