### ISSUE TITLE
Unable to Chisel Blocks or Place Bits in SMP

### ISSUE THREAD

**Issue by EricPfau** [ChiselsAndBits/Chisels-and-Bits#733] opened 2021-09-16 01:32 UTC
MC Version: 1.16.5
C&B Version: 1.0.1-ALPHA-universal
Do You have Optifine: No, only C&B installed for the purpose of this test.
Forge Version: 1.16.5-36.2.4

Details:
Currently only have C&B installed on both Client + Server. No other mods are installed. On Singleplayer C&B seems to work perfectly. Once on the server, Left-Clicking a block with a chisel while in creative mode causes the block to disappear, repeating the same in survival causes the block to flash but no bit is removed.

When attempting to place a bit in Creative or Singleplayer, the block almost looks like it gets placed for a split second, but then it's gone. 

All tests performed on a basic Stone block. Let me know if further information or testing is needed.

**Comment by marchermans** [comment] 2021-09-16 07:17
@EricPfau I need logs, screenshots, recordings, everything that you have that can help me, since I tried to reproduce this but I failed.

**Comment by EricPfau** [comment] 2021-09-16 16:26
I will do a fresh server install and retest just to be certain. Will provide you with as much relevant data as I can.

**Comment by marchermans** [comment] 2021-09-18 11:59
Reproduced. I will fix this.

**Comment by marchermans** [comment] 2021-09-24 16:09
Fixed in 1.0.2

**Closed as completed by marchermans** 2021-09-24 16:09 UTC
