### ISSUE TITLE
Forge 2557 crashes game whenever you pick something up

### ISSUE THREAD

**Issue by davqvist** [ChiselsAndBits/Chisels-and-Bits#333] opened 2017-12-01 10:54 UTC
https://pastebin.com/whxAsse1

Forge 2557 changed something in pickup code which makes it unplayable with C&B installed as you crash whenever you pick something up.

For any bug reports please provide the following,

* MC Version: 1.12.2 Forge 2557
* C&B Version: 14.9
* Do You have Optifine: No

**Comment by ghost** [comment] 2017-12-01 11:07
We posted at the same time, so I closed my issue (#334). My logs are posted there.

**Comment by TimGoll** [comment] 2017-12-01 13:16
Oh, I'm not alone. 
mine crashed too.

My report: [crashReport](https://gist.github.com/TimGoll/5630405f24973c2c3b2ab08d7e982b17)

**Comment by beesyndicate** [comment] 2017-12-01 13:26
https://pastebin.com/KkMM9Rrw

me too but some how my gut tells me this might be a forge problem.

for some reason I did not get a crash log but here is what I get from the terminal

forge-1.12.2-14.23.1.2557-universal
chiselsandbits-14.9
MC 1.12.2

**Comment by TimGoll** [comment] 2017-12-01 13:57
At least this issue only occurs with the newest forge verson

**Comment by AlgorithmX2** [comment] 2017-12-01 13:58
https://dvs1.progwml6.com/jenkins/job/Chisels-and-Bits/95/artifact/build/libs/chiselsandbits-14.0.95.jar - this build should work for the moment, Will release a standard release when I clear some other things up.

**Comment by TimGoll** [comment] 2017-12-01 13:59
Thanks. I downgraded the forge version. That works too

Edit: older forge version crashes too. Strange, worked yesterday

**Comment by AlgorithmX2** [comment] 2017-12-01 14:08
It should definitely work on an older version, the crash was caused by a change to a Forge Event, they removed a field and added a method instead. That change was made in 2557

**Comment by AlgorithmX2** [comment] 2017-12-01 21:41
Looks like Lex pushed a fix for this, https://github.com/MinecraftForge/MinecraftForge/commit/846a70f97fe9d270765cda3cbcf702e0ab99b8f5

So newer forge versions should resolve this.

**Closed as completed by AlgorithmX2** 2017-12-01 21:41 UTC
Labels: Third Party Issue
