### ISSUE TITLE
Chisel Design Cards for Multi-Block Selections

### ISSUE THREAD

**Issue by everseeking** [ChiselsAndBits/Chisels-and-Bits#212] opened 2016-12-28 01:06 UTC
### Enhancement Request

Create a new type of chisel design card which allows the copying and placement of multi-block designs.

Example: 

- The ability to copy [this entire front window](http://i.imgur.com/zEWaRAV.png) design (possibly by defining the cuboid corners "1" and "2") to easily paste in new location - without the need to copy each individual block of this multi-block "structure".

**Comment by AlgorithmX2** [comment] 2016-12-28 02:04
I find it unusual that this enhancement isn't already on the tracker...

This has been an ongoing project.. dates back to 1.9 or even earlier... I hope to one day finish it.

**Comment by everseeking** [comment] 2016-12-28 22:20
Yea I made sure to search all open/closed issues to maybe see if you already addressed it and couldn't feasibly implement it for some reason - I was surprised when I couldn't find anything. Sorry for spoiling the surprise if it was supposed to be one eventually, lol.

**Comment by AlgorithmX2** [comment] 2016-12-28 23:00
Not really, its a pretty wide known fact that I've been working on it for a while.. Its just a large project, and I don't have a lot of time, so I've been forced to put it on the back burner several times. 1.10.. 1.11 and such have all launched and required attention.

Time is a resource I tend to have very little of lately, and what time I do have tends to get sucked up in smaller things I can throw together in an hour, or into maintenance and bug hunts.

**Comment by weeryan17** [comment] 2016-12-29 17:48
Glad to see an issue of this out their. I never bothered because i knew several people already asked for it. I would suggest having a mode for coping blocks and then a mode for copying on a bits scale. simmilar to how the ruler has blocks and bits as two different options.

**Comment by AlgorithmX2** [comment] 2016-12-29 18:10
My current plan is to only deal with blocks, if you want to place smaller sections then doing that with shift+chiseled blocks or placement mode would be more suitable.

The blueprints will allow bit level offsets, but not bit level selection. Adding any more features to it will probably just delay it further.

**Comment by weeryan17** [comment] 2016-12-29 18:13
you could do block selection for the initial release of this and add bit selection later. I'm in no rush.

**Comment by maxashen** [comment] 2017-04-11 04:53
Out of curiosity what is your current plan for multiblock prints? From a gameplay perspective or implementation perspective?

I was thinking a sort of item where you select the structure a-la-ruler, then basically store it in an item nbt by calling getCompoundFromBlock() for each TileEntityBlockChiseled in the selection grid. For placement just do the same thing as with prints for each block in the structure.

**Comment by AlgorithmX2** [comment] 2017-04-11 07:00
The current idea is to set down the blue print item, use he wrench to size and shift it to capture the target, then capture it. then the deployment is similar, place it down , wrench it to position it, then build by right clicking on it or so so it uses bits and chisels to make the changes.

Most of this exists in a form, but its buggy and incomplete, and I just haven't had any amount of time to jump back in and finish it.

**Comment by za3k** [comment] 2017-05-04 06:37
@AlgorithmX2, you have another issue which requests import/export (as files on the computer system here), and it's marked as a duplicate of this. I'm adding this comment to make it clearer that that's included in your unfinished code

**Closed as completed** 2020-10-04 11:26 UTC
Labels: Enhancement
