### ISSUE TITLE
Forge Light Pipeline Issue

### ISSUE THREAD

**Issue by heyoomimi** [ChiselsAndBits/Chisels-and-Bits#146] opened 2016-10-05 15:09 UTC
I have Chisel-MC1.9.4-0.0.6.48 along with chiselsandbits-10.19, and when I tried placing grass, ferns, and flowers nearby, the lighting changes. ( http://prntscr.com/cq4zw5 vs. http://prntscr.com/cq51rv ) 
I disabled ForgeLightPipeline and although the lighting was fixed, the Chisels&Bits became wonky. ( http://prntscr.com/cq5e3j )

**Comment by AlgorithmX2** [comment] 2016-10-05 16:21
I tried disabling the forge pipeline in the latest version ( 12.4 ), and nothing seems to change.

The only time I've seen the erratic behavior your screenshots present is when Optifine was being used.

**Comment by heyoomimi** [comment] 2016-10-05 17:19
I don't use Optifine.

**Comment by AlgorithmX2** [comment] 2016-10-05 17:22
Can you provide any other details about the blocks that are not rendering properly? I believe I have tried each of the renderers and none of them seem to be failing, unless for some reason something has changed in 1.10.2 from 1.9.4 that would resolve whatever the problem is.

**Comment by Drullkus** [comment] 2016-10-05 18:09
We've already established that Chisel Blocks are having weird lighting issues but I'd like to link the tickets, Chisel-Team/Chisel#177.

I have absolutely no clue as to why your blocks would render like that in Vanilla lighting. Really weird :S

**Comment by falkreon** [comment] 2017-03-25 02:09
This problem showed up again in 13.10. Disabling the Forge light pipeline turns all chiselbits blocks into strange fans of triangles. All the triangles in a block share one vertex. I systematically disabled all other mods in the pack until I arrived at *just* C&B, and *just* the "B:forgeLightPipelineEnabled=false" setting in forge.cfg

Edit: I should also mention, MC 1.11.2 running Forge 13.20.0.2259

We'll just run with lighting enabled, haven't seen the lighting discrepancies the original poster reports anyway. I hope this helps track the issue down. I love this mod! :D

**Comment by AlgorithmX2** [comment] 2017-03-25 22:16
I extended the optifine check that disables custom vertex formats to also test for the forge lighting pipeline, without C&B cannot use custom vertext formats, which makes it similar to optifine in that since.

So it will disable the "glowing faces" features just like optifine does. I'll go ahead and close this now.

https://github.com/AlgorithmX2/Chisels-and-Bits/commit/d9f31074d05ce26864fd09266cc2b4ec8f110dc8

**Closed as completed by AlgorithmX2** 2017-03-25 22:16 UTC
Labels: Bug
