### ISSUE TITLE
[Fabric 1.19.3] CnB 1.3.132 for Fabric crash on startup

### ISSUE THREAD

**Issue by MilkissWhite** [ChiselsAndBits/Chisels-and-Bits#1088] opened 2023-03-20 22:12 UTC
Mincraft 1.19.3
 Fabric Loader 0.14.17
 Fabric API 0.76.0

 Chisels and Bits 1.3.132 for Fabric crash on startup(before title screen).

 Using CurseForge App for manage mods.
 tested profile have any other mods.
 here is my latest log.

https://hastebin.com/share/ilutuhurit.sql

**Comment by c0du** [comment] 2023-03-20 23:14
Also crashing on startup before the title screen. I've made a clean instance with just C&B with the same result.

**Comment by jpower123** [comment] 2023-03-21 01:24
I can confirm I am having the same issue. I have a feeling that the newest release is not made for fabric, even though it says that it is. I only think this because the changelog on curse says "updated to latest forge version"

**Comment by marchermans** [comment] 2023-03-21 09:50
Fixed in 1.3.333

**Closed as completed by marchermans** 2023-03-21 09:50 UTC
