### ISSUE TITLE
[1.12.2] World crashes upon loading after I placed bits

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#322] opened 2017-11-08 17:02 UTC
I placed bits on a wall and instantly crashed.

**Crash log:** https://pastebin.com/raw/nNfjEErb

After I placed some bits and my world crashed, I couldn’t access the world anymore, so I had to restore to a backup since my world basically became corrupt.

**Minecraft version:** 1.12.2
**Modpack:** [All the Mods 3](https://minecraft.curseforge.com/projects/all-the-mods-3), v. 4.4
**Chisels & Bits version:** 14.9
**MCMultiPart version:** 2.3.3

I do have OptiFine.

**Comment by AlgorithmX2** [comment] 2017-11-08 19:35
This looks to be a duplicate of https://github.com/AlgorithmX2/Chisels-and-Bits/issues/310 more missing worlds from MCMP
https://github.com/AlgorithmX2/Chisels-and-Bits/blob/ffc9e633a01305c1efdd0b6aa81d1545b4e5ba24/src/main/java/mod/chiselsandbits/chiseledblock/BlockChiseled.java#L513

@amadornes any progress on these issues???

**Closed as completed by AlgorithmX2** 2017-11-08 19:35 UTC
Labels: Duplicate
