### ISSUE TITLE
Game breaking bugs!

### ISSUE THREAD

**Issue by aidancorgi** [ChiselsAndBits/Chisels-and-Bits#573] opened 2021-01-04 02:12 UTC
Hello, I just started playing this mod and wanted to start a major project. I honestly love this mod, it is super underrated. However, I just have so much trouble with the mod. I have currently no other mods but this in my mod folder.  My first problem is that when I try to place bits on top of blocks using the single bit mod, it never touches, it always skips and floats over this. Another problem, when using the paint mode, after trying to make it wider than about 4 bits it floats on the bottom. I know these sound confusing but they will make sense once I post the video. A minor problem is when changing bit mode, it freezing my character movement, all I have to do is to open the menu and close it, and it's good. One last problem I have is sometimes when I try to place a bit in a spot, it places a block different from where the crosshair is located. I really hope these problems can get fixed. These problems make the building so much longer.

here is the video
https://drive.google.com/file/d/18zURPRZ1jFh09JV_9qtvhYKFGOx34NNR/view?usp=sharing

* MC Version:1.16.4
* C&B Version:0.2.8
* Do You have Optifine: No

**Comment by aidancorgi** [comment] 2021-01-04 03:15
P.S. Using the draw region mode delete mode works how the place mode should work. In the first part I show how the destroy works, second I show how buggy and behind placing mode is. https://drive.google.com/file/d/1-gNrmCHMiV8SF4Lf1zQwLjBBRzyv9phC/view?usp=sharing

**Comment by Adrakaris** [comment] 2021-01-04 11:01
I'm pretty sure this is already known issue and awaiting commit.

**Comment by marchermans** [comment] 2021-01-04 11:41
This is known and a duplicate of: #569

**Closed as completed by marchermans** 2021-01-04 11:41 UTC
