### ISSUE TITLE
[1.12.2] Thin covers disappear from render

### ISSUE THREAD

**Issue by kvgeorge1** [ChiselsAndBits/Chisels-and-Bits#345] opened 2017-12-13 03:41 UTC
I am using MCMultiPart along with C&B.  I created some vertical covers and covered some Refined Storage cables.  All seemed well so I logged off.  When I can back on, the covers (and now the cables) are invisible, but the RS storage elements are still working - even though it looks as though there is no cable connected.  When I try to break the invisible blocks, or place blocks to get them to show up, I am unable to retrieve what is there.

For any bug reports please provide the following,

* MC Version:  Forge 14.23.1.2555 (MC: 1.12.2)
* C&B Version: 14.11
* Do You have Optifine:  No, but I am using BetterFPS Mod

**Comment by AlgorithmX2** [comment] 2017-12-13 04:20
Duplicate of https://github.com/AlgorithmX2/Chisels-and-Bits/issues/310 ( I know the name ~~is~~was misleading )

Summary of the story is that the issue is with MCMP, and that if you check your log you'll notice there is a refined storage exception thrown there because it tries to handle a packet without access to the world.

I can't do anything to fix it, but you can subscribe to the other issue if you want to keep up to date as things develop. If they do. You can also read up on whats going on in related MCMP related issues there if you so wish.

**Closed as completed by AlgorithmX2** 2017-12-13 04:20 UTC
Labels: Duplicate, Invalid
