### ISSUE TITLE
Cannot interact with any block using C&B

### ISSUE THREAD

**Issue by BloodRedstone** [ChiselsAndBits/Chisels-and-Bits#744] opened 2021-10-03 22:44 UTC
* MC Version: 1.16.5
* C&B Version: 1.0.11
* Do You have Optifine: Yes

I don't know how or why, but whenever I attempt to hit or place bits with a chisel or otherwise, the block i am interacting with completely flashes invisible before reappearing unchanged.

I have a few mods and i am non a server, i dont think any of them should affect it because theyre mostly structure and mob pack mods

i wish i could give you more, but i dont have any idea how or why this is happening to me as others with identical mod folders dont have this problem

**Comment by BloodRedstone** [comment] 2021-10-03 22:52
so nothing is fixed yet, but i got the error OpenGL Error 1281 in chat from optifine when i tried to break a block this time

**Comment by marchermans** [comment] 2021-10-04 00:51
Optifine is known to cause this. Besides this i would need logs from both the client and the server (if you are on one)

**Comment by BloodRedstone** [comment] 2021-10-04 02:28
so i dont know if this helps, but now ive removed optifine, and i still cannot chisel blocks or place chisel. (the blocks just dont change, instead of flashing transparent) i am on a server and i do not have access to server logs, ive also noticed that whenever the server automatically restarted i can chisel again for a bit before it breaks again, most likely a serverside issue somehow, just thought i should respond with this info

**Comment by marchermans** [comment] 2021-10-04 10:45
Okey.
Then ask your server owner to provide the logs here.

Because I can reproduce this, and without the logs I am not sure how to help you......

**Comment by SavageLykos** [comment] 2021-10-09 04:16
I am having the similar issue issue I was using chisel and bits and I died. After that I am unable to use the mod. I asked the server owner for the logs and he is stating there are none and he is also able to use it. Another bug I found is the chisel bag crashes my client anytime I try to pull chisels from it while placing down more than I have in my hand
[crash-2021-10-08_20.56.05-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7314953/crash-2021-10-08_20.56.05-client.txt)
.
update: deleting client files for c&b fixed the issue with being unable to interact with the mod for now.

**Comment by ZaqeoLog** [comment] 2021-10-13 10:14
I've been having the same problem. I ignored it and after a while it got fixed and I was able to place and break things. I left the server and came back after a few hours but it went back to not working.

**Comment by marchermans** [comment] 2021-10-13 10:58
Fixed in the newest release.
There was a bug with regards to timing.

**Closed as completed by marchermans** 2021-10-13 10:58 UTC
Labels: Bug, Performance Enhancing Mods, Priority: Low
