### ISSUE TITLE
minecraft crashes

### ISSUE THREAD

**Issue by kaindand** [ChiselsAndBits/Chisels-and-Bits#1102] opened 2023-04-26 13:40 UTC
every time I create a new world and edit blocks with the mod, it crashes. At first it starts to lag, and then after a while it crashes and you can no longer enter the world. i5 11400 and 3060 t i and other mods are not installed

**Comment by marchermans** [comment] 2023-04-26 13:44
Can I get a log from this?

**Comment by kaindand** [comment] 2023-04-26 15:11
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "mod.chiselsandbits.platforms.core.registries.deferred.IRegistryObject.get()" because "convertedItemProvider" is null

**Comment by marchermans** [comment] 2023-04-26 15:45
What game version or mod version of are you running?

**Comment by kaindand** [comment] 2023-04-26 16:00
1.18.2

**Comment by kaindand** [comment] 2023-04-27 10:49
ChiselsBits-fabric-1.18.2-1.2.116

**Comment by marchermans** [comment] 2023-04-30 21:09
I can not reproduce this.
And it is a duplicate of #977

**Closed as completed by marchermans** 2023-04-30 21:09 UTC
