### ISSUE TITLE
[suggestion] ability to import/export designs

### ISSUE THREAD

**Issue by SnowsongWolf** [ChiselsAndBits/Chisels-and-Bits#413] opened 2018-08-03 14:13 UTC
I would like to see the ability to import and export blueprints locally, for cross server or simply archival purposes. It would also open to the ability to share designs between users.

**Comment by AlgorithmX2** [comment] 2018-08-04 01:29
Think this is sort of a duplicate of https://github.com/AlgorithmX2/Chisels-and-Bits/issues/337

**Closed as completed by AlgorithmX2** 2018-08-04 01:29 UTC
Labels: Duplicate
