### ISSUE TITLE
C&B not working in survival and creative

### ISSUE THREAD

**Issue by Pichumari** [ChiselsAndBits/Chisels-and-Bits#550] opened 2020-12-09 16:15 UTC
C&B unexpectedly stopped working one day. I’ve removed SEVERAL mods and plugins and nothing seemed to be conflicting as it stayed the same. In survival people are having issues placing bits, having issues with contents of bit bags disappearing, and papers not copying and pasting designs. In creative you can sometimes place bits, but copying the design using the scroll wheel turns your inventory slot into chiseled cobblestone and it’s invisible and can’t be placed. You also cannot touch chiseled designs that are stacked in chests without corrupting them into the invisible cobble glitch too... I’ve tried so much- we can’t update our forge version because it would conflict with other mods we have in our pack. I can’t think of anything that’s conflicting as this was completely random and out of the blue. C&B is a staple on our server, it would be great if we got an answer of some sort. :(

**Comment by Pichumari** [comment] 2020-12-09 16:19
MC Version: 1.12.2
C&B Version: 14.17
Forge Version: 14.23.5.2847
Do You have Optifine: No

**Comment by Pichumari** [comment] 2020-12-09 16:36
List of mods and their versions:
AppleSkin 1.0.9
Baubles 1.12-1.5.2
BiblioCraft 2.4.5
Biome Bundle O Plenty 1.0
Biomes O’ Plenty 7.0.1
Botanic r1.10-360
Chameleon 1.12-4.1.3
ChinjufuMod 5.1.3
Chisel MC1.12.2-1.0.2.45
Chisels & Bits 14.17
Construct’s Armory 1.12.2-1.2.5.3
Cooking for Blockheads 6.5.0
CTM MC1.12.2-1.0.2.31
CustomNPCs 1.12
Davinci’s Vessels 1.12-6.340
Decocraft 2.6.2_1.12.2
DrZhark’s CustomSpawner 3.11.4
DrZhark’s Mo’Creatures 12.0.5
Electroblob’s Wizardry 4.2.11
Extra Utilities 2
Flat Colored Blocks MC1.13-6.6
Forge Mod Loader 8.0.99.99
Future Versions 1.3.0.2
Hammer Core 2.0.6.17
Inventory Tweaks 1.63+release.109.220f
Just Enough Items 4.15.0.268
Mantle 1.3.3.55
Minecraft 1.12.2
Minecraft Coder Pack 9.42
Minecraft Forge 14.23.5.2847
Minerva Library 1.0.13
Moving World 1.12-6.353
MovingWorld CORE
MrCrayfish’s Furniture Mod 6.3.0
NoMoreRecipeConflict 0.13
Open Terrain Generator 1.12.2 V8.3
OTG Core 1.12.2 V8.3
Outfox 0.1.5
Pam’s HarvestCraft 1.12a
Patchouli 1.0-19
Placebo 1.12.2-1.6.0
Plants 1.12.2-2.10.7
Ptrmodellib 1.0.3
Rustic 1.1.4
Storage Drawers 1.12.2-5.4.2
TeaStory 3.3.3-B32.404-1.12.2
Thaumcraft 6.1BETA26
Thaumic Additions 12.4.3
Thaumic Gadgets 0.1.5.0
Thaumic Tinkerer 1.12.2-5.0-7fa190f
Tinkers Tool Leveling 1.12.2-1.1.0
Tinkers’ Construct 1.12.2-2.13.0.183
Traveler’s Backpack 1.0.34
Tree Chopper 1.2.4
Waila 1.8.26

**Comment by marchermans** [comment] 2020-12-09 18:36
Sorry 1.12 is at this time not supported anymore .
But this seems to be somewhat critically game breaking so j make an exception.

First we need all the logs you can get. From the server from clients as much as you can find.
Then I need to know if you updated the mod pack recently.
Then i need to know if it happens in a single player world.

See if you can get that data. And I might be able to help you. But no promises.

**Comment by Pichumari** [comment] 2020-12-09 21:55
Here is some of my servers logs:
[[2020-12-09-1-2.log](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/5668860/2020-12-09-1-2.log)](url)
As for updating the mod pack? We have only updated it recently to attempt to fix this. We removed mods and plugins to see if they were conflicting and when I saw they weren't I did a rollback and everything is back in our files.
And yes, it's happening in single player too.
Also this is the first I am hearing about 1.12 not being supported anymore? Is this part of the issue?
Thanks for at least looking into it a bit! :)

**Comment by slaaayx** [comment] 2020-12-20 02:03
Hi,

I have had the exact same problem like you, I have a mixture of forge and paper as a minecraft server. You need to go to the config of your server, then open the chiselandbits.cfg. After that you will need to look up the first category "balance settings", you need to set "requireBagSpace" to true and set the "bagStackSize" to 127. This worked for me, when I put 255 for example, it doesn't work for me. I think it is capped by a setting that limits that inside of the jar file of the forge server.

**Comment by marchermans** [comment] 2021-01-09 15:05
Since I have no clue what the cause is and this is for an unsupported version.
I will close this now.

**Closed as completed by marchermans** 2021-01-09 15:05 UTC
Labels: Bug, Not supported MC Version
