### ISSUE TITLE
Invisible blocks, might found the cause. 

### ISSUE THREAD

**Issue by Wastafari** [ChiselsAndBits/Chisels-and-Bits#431] opened 2018-09-10 20:16 UTC
![chisel and decocraft](https://user-images.githubusercontent.com/43152227/45321267-24d35280-b545-11e8-931a-5d7b0e052a97.png)

Decocrafts item's who also got affected and changed appearence, there is beer barrels and a table in this pic, C&B went totaly invisible.
Some of my chisel and bits things randomly dissapears, or go invisible. But there is som realisations I've made.  This is my second world who gets corrupted by this "bug" or mod incompabillity. 
Already read a couple of threads about this issue. Links further down. 
After some quick inverstergation it is only caused in one chunk. First time this happend it was Pam's harvestcraft's ground traps who made this effect. This time It is probably Decocraft. In this chunk were most C&B was gone there was also alot of Decocraft items. Most of them had some kind of inventoryspace. I can't reproduce this without C&B installed.  I have no idea what might cause it to do this. 

Is this even something that you can look at or is this just some mods that just don't work together?

- https://github.com/AlgorithmX2/Chisels-and-Bits/issues/118

- https://github.com/AlgorithmX2/Chisels-and-Bits/issues/241

I'm using MC 1.12.2
with C&B 14.18
and optifine. 

Playing with Welsknight's modpack Nature's beauty without Pam's

**Comment by Wastafari** [comment] 2018-09-10 20:24
Quick notice: Even by removing Decocraft C&B is still invisible.

**Comment by AlgorithmX2** [comment] 2018-09-10 20:26
Generally this sort of issue is caused by unbalanced render code.

It tends to be specific to one item, or block as the "cause" basically in the renderer it does something, then forgets to undo it.

Which usually means its difficult to track down besides, Just start removing blocks or such things and make note of when the affected blocks stop being affected.

If its inside of one chunk only you might have some luck with that.

**Comment by Wastafari** [comment] 2018-09-10 20:29
ok, I will work around and see if I can find anything that can make it render correct. Will post if I find something interesting! Thank you for this mod and your time!

**Comment by Wastafari** [comment] 2018-09-10 20:42
After poking around for a bit the game just crashed and the world is really F#% up. not many blocks are what the were.. Is a crash report anything that you want to see?

**Comment by AlgorithmX2** [comment] 2018-09-10 20:44
You can certainly post it, if blocks are changing it sounds like something corrupted the save though.

**Comment by Wastafari** [comment] 2018-09-10 20:45
[crash-2018-09-10_22.39.17-client.txt](https://github.com/AlgorithmX2/Chisels-and-Bits/files/2368321/crash-2018-09-10_22.39.17-client.txt)
Yeah, something is seriously wrong now. Dunno if it was to much poking and test remove some other mod items that was in that chunk.. well well.

**Comment by AlgorithmX2** [comment] 2018-09-10 20:49
The cause is related to,
	at elucent.elulib.tile.multiblock.TileModularSlave.hasCapability(TileModularSlave.java:54)
	at mrriegel.limelib.tile.IHUDProvider.isHUDProvider(IHUDProvider.java:42)
	at mrriegel.limelib.util.ClientEventHandler.render(ClientEventHandler.java:154)

Hard to say whats going on there, EluLib and LimeLib. of course it might be a red herring if the world is as messed up as you say.

**Comment by Wastafari** [comment] 2018-09-10 21:02
Might be something else that caused C&B to malfunction and now this happend beacuse of me. Will do some more testing without some of the not so important mods and se if it happens again, If so I will come back. For now I'll start a new world and begin building my way up agian. 
Thank you again for an amazing work with the mod and in the community!

**Comment by AlgorithmX2** [comment] 2019-01-23 01:26
For lack of anything that I think I can do here, I'm going to close this issue.

**Closed as completed by AlgorithmX2** 2019-01-23 01:26 UTC
Labels: Invalid
