### ISSUE TITLE
Block Placement Glitch

### ISSUE THREAD

**Issue by iGhoztman** [ChiselsAndBits/Chisels-and-Bits#557] opened 2020-12-13 21:17 UTC
When placing bits, the bits don't place in the right spot. 

![chisel and bits glitch-min](https://user-images.githubusercontent.com/75952935/102024174-63789880-3d5e-11eb-89bf-eb0b8780cbc3.gif)

For any bug reports please provide the following details as well,
* MC Version: 1.16.4
* C&B Version: 0.2.8
* Do You have Optifine: Yes

**Comment by marchermans** [comment] 2020-12-13 21:19
Duplicate of: #549

**Closed as completed by marchermans** 2020-12-13 21:19 UTC
Labels: Bug, Duplicate
