### ISSUE TITLE
JEI and Chisels & Bits crashes in 1.16.3

### ISSUE THREAD

**Issue by rehwinkel** [ChiselsAndBits/Chisels-and-Bits#521] opened 2020-10-20 07:43 UTC
When running Chisels & Bits with JEI, the game crashes with the following stack trace:

```
Description: Rendering ingredient

java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_265] {}
	at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_265] {}
	at net.minecraft.util.NonNullList.get(SourceFile:46) ~[?:?] {re:classloading}
	at mod.chiselsandbits.render.bit.BitItemSmartModel.getCachedModel(BitItemSmartModel.java:45) ~[?:?] {re:classloading}
	at mod.chiselsandbits.render.bit.BitItemSmartModel.func_239290_a_(BitItemSmartModel.java:82) ~[?:?] {re:classloading}
	at mod.chiselsandbits.client.model.baked.BaseSmartModel$OverrideHelper.func_239290_a_(BaseSmartModel.java:43) ~[?:?] {re:classloading}
	at mezz.jei.render.ItemStackFastRenderer.getBakedModel(ItemStackFastRenderer.java:40) ~[?:7.6.0.49] {re:classloading}
	at mezz.jei.render.ItemStackFastRenderer.uncheckedRenderItemAndEffectIntoGUI(ItemStackFastRenderer.java:50) ~[?:7.6.0.49] {re:classloading}
	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:29) ~[?:7.6.0.49] {re:classloading}
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:170) ~[?:7.6.0.49] {re:classloading}
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:123) ~[?:7.6.0.49] {re:classloading}
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:108) ~[?:7.6.0.49] {re:classloading}
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:170) ~[?:7.6.0.49] {re:classloading}
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:85) ~[?:7.6.0.49] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_164_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraft.client.gui.screen.Screen.func_238651_a_(Screen.java:350) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.func_230446_a_(Screen.java:344) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_230430_a_(SourceFile:83) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:281) ~[?:?] {re:classloading}
```

For any bug reports please provide the following details as well,
* MC Version: 1.16.3
* C&B Version: built from commit a6c1e48b14bb54cb7b3f8c3a2c320a808c0e5238
* Do You have Optifine: Yes

**Comment by Aeltumn** [comment] 2020-10-20 08:27
Duplicate of #519

**Closed as completed by Aeltumn** 2020-10-20 08:27 UTC
Labels: Duplicate
