### ISSUE TITLE
Hello Im currently playing Valhelsia 3 and when I accidently chiseld a cobblestone block something weird happend. I can see that the cobblestone block is missing 2 little bits but i cant INTERACT with the block anymore. The block is just there and I cant do anything to get rid of it.

### ISSUE THREAD

**Issue by linksko** [ChiselsAndBits/Chisels-and-Bits#622] opened 2021-02-16 16:14 UTC
Hello Im currently playing Valhelsia 3 and when I accidently chiseld a cobblestone block something weird happend. I can see that the cobblestone block is missing 2 little bits but i cant INTERACT with the block anymore. The block is just there and I cant do anything to get rid of it. They game seems to think that the block doesnt exist as I cant get the grid that you get when your cursor is on a block. PLEASE Help

![image](https://user-images.githubusercontent.com/79157971/108089770-415f0780-707a-11eb-9851-a19c4f615b17.png)

**Comment by GhostWing404** [comment] 2021-02-26 05:00
this same thing just happened to me except its and iron block and all the bits are off by 1 bit when placed i have no idea why tho i was really excited when the mod updated but its Super glitchy

**Comment by GhostWing404** [comment] 2021-02-26 05:02
if you have world edit you can remove it by making sure its in a selection and doing //cut

**Comment by alpharou** [comment] 2021-02-27 23:58
Can confirm, version 0.2.10 release has passthrough problems

Other people on server can break and interact with the chiseled blocks

**Comment by marchermans** [comment] 2021-03-07 12:42
Can you guys check if this is fixed in 0.3.0.

I updated the synchronization and save mechanics.

**Comment by ItSammyboi** [comment] 2021-03-10 15:40
yep. the same thing just happened to me. I was working on a custom block and it suddenly just stopped "doing" like it was there, it had collision with my body but I couldn't remove it or interact with it.

**Comment by marchermans** [comment] 2021-03-10 20:15
I really can't reproduce this.
Does it stay after a relog?

**Comment by Domek97** [comment] 2021-03-16 00:08
This is happening to me right now. I crawled and started breaking if that makes any difference. A relog does not fix it but I somehow got it to fix itself when it happened earlier. Would also probably help to mention that i was in creative.

EDIT: using tnt to blow up the block will get rid of it and solve the issue

**Comment by marchermans** [comment] 2021-03-16 13:01
I have a world where i chiseled every block as far as the eye can see. And I was not able to reproduce this in anyway shape or form.

Could you see if you can reproduce this somehow.

**Comment by Sakamoto0110** [comment] 2021-03-18 13:14
Hey, i'm having a similar bug, every second use of the chissel is making the block un-interactible, but still exists in world, tried with wooden planks and andesite.
I created a copy of the latest log after doing this.

![2021-03-18_10 05 29](https://user-images.githubusercontent.com/41306027/111631394-1af3cf80-87d2-11eb-9ec9-e5e2e592d5a0.png)

**Comment by SkyTheNerd** [comment] 2021-03-19 16:04
This happened to me too, but I found out you can use /fill to get rid of it.

**Comment by Domek97** [comment] 2021-03-20 22:55
> 
> 
> I have a world where i chiseled every block as far as the eye can see. And I was not able to reproduce this in anyway shape or form.
> 
> Could you see if you can reproduce this somehow.

I think I discovered what causes the bug. I've most commonly gotten it to occur when shaping blocks to look like normal stairs but without using the setting "1/2 size cube" to do it. For instance, I use "1/4 size cube" to make the stair shape and as i complete the shape the block will be uninteractible. It doesn't do it all the time, but then again the bug doesn't happen every time I chisel blocks. I also made my roof entirely off of blocks chiseled into shapes of stairs and used "1/2 size cube" to do it and it never caused the bug.

When i use this method it occurs about 40% of the time

**Comment by Domek97** [comment] 2021-03-20 23:23
I've discovered a workaround for the time being. if you can place a chiseled block onto the uninteractible block by using a block next to it it makes the block interactible again. I don't know what Sky is talking about with /fill though

**Comment by marchermans** [comment] 2021-03-21 14:07
@Domek97 Are you on a server or not?

I just tried this in a Single player world. It does not happen for me.

**Comment by Yaikez** [comment] 2021-05-17 08:19
I found a "solution". Basically you need to but bits in that missing block by placing them with a block underneath it. The block I was working on had a missing plane so it was easy to place bits in it but if you miss 1 or 2 bits I don't know if you need to put them in that specific position or it just needs to be in it. (playing in 0.3.4 version)
Edit: I additionally discovered that it does this bug just in a specific direction (ex. if i chisel out bits from the west part of the block it glitches, otherwise it doesn't)

**Comment by marchermans** [comment] 2021-09-28 19:30
Fixed in the latest 1.0.8-BETA

**Closed as completed by marchermans** 2021-09-28 19:30 UTC
Labels: Bug, Requires Research, Waiting On Response, Priority: High
