### ISSUE TITLE
Crash: placing chisel and bits on Refined Storage pipes

### ISSUE THREAD

**Issue by MRVDOG** [ChiselsAndBits/Chisels-and-Bits#330] opened 2017-11-23 20:36 UTC
I placed down a Refined Storage crafting grid and pipes, and wanted to cover them up, so I got some of my bits and noticed it showed I could add bits directly to the pipe, I did so and it crashed my client, now I'm getting weird bugs in the chunk, from models becoming invisible, to transfer nodes becoming a textureless block, to the pipes becoming invisible with no hitbox, only seems to be the chunk where the broken pipe is that is affected, we're running the pack on TLove's sub server, I requested a restart and it crashed instantly

https://ss.mrvdog.com/1219ISHJfW7.gif
![](https://ss.mrvdog.com/1216W5CRpVL.thumb)
![](https://ss.mrvdog.com/1217nIOpwF9.thumb)

* Mod Pack : Direwolf20 1.1.0
* MC Version: 1.12.2
* C&B Version: 14.9
* Do You have Optifine: No

**Comment by MaddoScientisto** [comment] 2017-11-23 23:46
That happened to me on direwolf 1.12 too, to fix it I had to open the map in mcedit and manually delete the offending block, after that the chunk loaded properly

**Comment by AlgorithmX2** [comment] 2017-11-24 00:48
I think this is duplicate of https://github.com/AlgorithmX2/Chisels-and-Bits/issues/310

@amadornes hasn't responded.

**Closed as completed** 2017-11-24 07:07 UTC
Labels: Duplicate
