### ISSUE TITLE
Chiseling blocks causes substantial lag in the rebuild version

### ISSUE THREAD

**Issue by AceSevenFive** [ChiselsAndBits/Chisels-and-Bits#716] opened 2021-08-21 01:31 UTC
* MC Version: 1.16.5
* C&B Version: 1.0.0 rebuild
* Do You have Optifine: Yes (though I can reproduce the bug without Optifine installed)

**Comment by marchermans** [comment] 2021-08-24 06:19
This is known.
I am currently trying to track down the cause.

**Comment by marchermans** [comment] 2021-09-25 20:40
Fixed in the latest beta.

**Comment by dannydjdk** [comment] 2021-09-29 14:17
This does not appear to be entirely fixed in 1.0.9. I have a build with a large number of chiseled blocks. In 0.3.4, there is a tiny amount of block lag associated with the build. Opening and closing doors, for instance, causes a barely noticeable stutter. In 1.0.9, opening a door or placing blocks in that chunk causes the game to lock up for several seconds each time while the chunk redraws.

I've tried this on 2 different computers with completely different configurations with the same result. Also in 1.12.2, a similar build causes no lag at all. I suspect that has much to do with Minecraft being less efficient, but I wanted to mention it just to rule out issues with my setup.

**Comment by marchermans** [comment] 2021-09-29 19:19
Can you please run a Spark Client Profile @dannydjdk ?

**Comment by marchermans** [comment] 2021-09-29 20:00
I tracked some of that overhead to the cache implementation.
I will see what I can do in the next few releases to reduce that.

**Comment by dannydjdk** [comment] 2021-09-30 01:09
Would you still like a Spark client profile? I can try to narrow down the pack if that's useful, but it would take bit longer, as I'd probably have to put a new build together.

**Comment by marchermans** [comment] 2021-09-30 18:17
I have been tracking it with some body in our discord

**Comment by dannydjdk** [comment] 2021-09-30 19:56
Sounds good. Let me know if anything comes up I can help with.

**Comment by dannydjdk** [comment] 2021-10-02 20:12
You probably already know this, but 1.0.10 is screaming fast!!! Same build as above with many chiseled blocks, and there is no noticeable block lag at all. It's even better than 0.3.4.

Thank you!!!!

**Comment by marchermans** [comment] 2021-10-03 11:39
Fixed properly in 1.0.11 or 1.1.5 depending on your mc version

**Closed as completed by marchermans** 2021-10-03 11:39 UTC
Labels: Bug, Performance, Priority: High
