### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Trixz2018** [ChiselsAndBits/Chisels-and-Bits#346] opened 2017-12-13 09:44 UTC
https://pastebin.com/Xe9T12E1

For any bug reports please provide the following,

* MC Version: 1.12
* C&B Version: 14.10
* Do You have Optifine: no

After installing the calculator mod along with its core mod i got this crash. Once removed everything was fine. If need be i will let the mod author know about this.

**Comment by AlgorithmX2** [comment] 2017-12-13 15:39
You just need to update to C&B 14.11

Duplicate of ( https://github.com/AlgorithmX2/Chisels-and-Bits/issues/342 )

**Closed as completed by AlgorithmX2** 2017-12-13 15:39 UTC
Labels: Duplicate
