### ISSUE TITLE
Missplaced blocks, dissapearing and duplicating bits, suggestion, thank you

### ISSUE THREAD

**Issue by Terra777** [ChiselsAndBits/Chisels-and-Bits#572] opened 2021-01-02 01:37 UTC
For any bug reports please provide the following details as well,
* MC Version: 1.16.4
* C&B Version: Release 0.2.8.
* Do You have Optifine: YES.

Hi. I want to preface this by saying one thing. I am using this mod in a modpack and am aware that this might cause an issue with the mod. Modpack is fully updated, current version of Valhelsia 3. However, i do believe these bugs are caused by instability of the release itself because i have not actually used the mod with any modded blocks.

Now that we got that out of the way, if you are still reading it/care the issues are following:

a) When placing a chiseled bit of any block (vanilla) in this specific case orange terracota i experience issues of wrong placement of the block itself. 

The way this happens is: I want to place chiseled bit piece in a corner of my house. The corner is lets say front left and bottom corner of the house. If i per say click with a chiseled bit on the left wall of the house, regardless of where it is and regardless of what mode i am in (bit size) the bit will be placed into a block adjacent to the corner. Basically, it will be placed dead ass in the air of the block to the RIGHT of the corner. And it happens every time, always, with any block i used so far. Also, once that happens, if i try placing any bits in the corner block it would appear they will completely vanish, or to be more exact it seems as if i am placing down air. I apologize, i have not followed exactly if they got used up but i do not believe they did. If i undo the placements where it seemed i placed air it basically does not allow it. It seems as if i never placed anything. Basically confirming to me that the game does not think i ever placed anything eventho the animation went through. ( I can still freely put the block into the space as well) this also happens on another side of the block. The way to circumwent this happening is if instead of clicking to the LEFT wall of the corner you click on the BOTTOM block or you place a bit with clicking on top of the "FLOOR" block. That will place the bit in desired location without any issues.

Edit: Just noticed this was mentioned already but in effort to place new light onto this issue possibility, indeed i have noticed this is primarily issue with grid locked placement and drawn region. If i cut out single bit from a region, go to replace that region with another bit it would add an additional bit layer on top of that. As if you can never get a single bit fill out. (Drawn region command)

b) I believe this is connected to the previous issue of "placing nothing" but basically the issue is that the chisel bit bag bugs out.
Not entirely sure how to reproduce this one but all i will say is what happens is following:
I choose a bit that i got a full bag off, lets say stack started at 12 bits in my hotbar. And then i use up those 12 bits, it will never offer me new bits in hand even if i have the bits in the bag. Also, ( i can not confirm this) but for some reason i feel like i experienced some bits just vanishing or even duplicating (was really hard for me to actually notice it but if i had bits somewhere, i would use a single bit and they would dissapear and then i would not be sure if i actually had them in first place etc, that sorta thing, would happen randomly really).

Suggestion:

Please, in future, when you are not busy with obviously making this fully polished i would love it if there could be a config setting where we could determine the amount of blocks we can have in the bag, or just a bit bag upgrade that we could bring to extremely large amount of bits.

Thank you:

Thank you for bringing this mod to 1.16.4. i have been waiting for extremely long for this. And i love it with all the bugs and issues. I do not really mind them at all. All i wish is to help you in any way i can to improve our collective experience. You should really have somewhere people can send you images of what they create with your mod so you can get inspired. All i need now is LittleTiles to update to 1.16.4 and be compatible with c&b and basically got everythin i ever needed in life. Lmao. Thank you again. Enjoy. P.S. I can provide a video of the missplaced bits if there is a need. Tho my upload speed is trash so gonna only be few secs. Good night (2:40 am) zzzzzzzzzzzzzzz

**Comment by NielsPilgaard** [comment] 2021-01-08 20:41
Here's a video of the bug: https://streamable.com/651rxq

**Comment by marchermans** [comment] 2021-01-09 15:02
Duplicate of #549.

**Closed as completed by marchermans** 2021-01-09 15:02 UTC
Labels: Bug, Duplicate
