### ISSUE TITLE
Regular Minecraft Glass in 1.10.2 not rendering as a half block

### ISSUE THREAD

**Issue by RepoDraghon** [ChiselsAndBits/Chisels-and-Bits#279] opened 2017-06-18 01:30 UTC
For any bug reports please provide the following,

* MC Version: 1.10.2
* C&B Version: 12.12
* Do You have Optifine: yes U_D7
![2017-06-17_18 23 10](https://user-images.githubusercontent.com/8423696/27257425-f3b8c698-538a-11e7-860f-c75fa3508032.png)

**Comment by RepoDraghon** [comment] 2017-06-18 02:03
Correction, seems anything I place is not showing up now... but previously done things are rendering... cause crass is doing the same thing...

**Comment by AlgorithmX2** [comment] 2017-06-18 02:07
Seems like this is a duplicate of https://github.com/AlgorithmX2/Chisels-and-Bits/issues/277 some kinda of odd optifine related issue.  I don't know why that closed the last issue.

**Comment by RepoDraghon** [comment] 2017-06-18 02:09
I'm sorry, I did a search for this issue and didn't find anything... Thanks for the link...

**Comment by AlgorithmX2** [comment] 2017-06-18 02:12
I guess just leave this one open instead, like I said, Not sure why they closed it, I wish tracking down optifine related issues was easy... but its not and not being easy means I can't just try and figure it out in fifteen minutes when I have a few minutes.

Oddly though they said that had no issues on 12.12, and said the issue appeared in 12.13/12.14 but your seeing it on 12.12.

If any devs want to feel free to look into this sort of thing, I honestly have no idea when I'll be able to get to it.

**Comment by RepoDraghon** [comment] 2017-06-18 02:20
none of my settings or versions of Optifine have changed, it only happened when updating C&B and other mods

**Comment by RepoDraghon** [comment] 2017-06-18 02:31
It might also be worthy to note that I am using a combined Direwolf 1.10.2 and Hermitpack, plus a few minor other mods

**Comment by PSILONCRAFT** [comment] 2017-06-18 17:20
I have the same issue and I'm running a custom mudpack called project psiloncrafted. this issue happened after i upgraded to ver 12.12

**Comment by AlgorithmX2** [comment] 2017-06-20 17:19
Can anyone confirm that it is in fact optifine causing the issue? and not a second mod? Or configuration? I'm mostly guessing that it was optifine at this point since I was unable to re-create it with just C&B.

If it isn't optifine tracking down what mod would also help. Finding the minimal recreation conditions always helps.

**Comment by PSILONCRAFT** [comment] 2017-06-20 17:28
I updated the CTM mod and that fixed it for me

**Comment by PSILONCRAFT** [comment] 2017-06-20 17:53
yea. connected texture mod fixed the problem I'm now running 12.12 ver of c&b with latest CTM (beta and optifine D8

**Comment by AlgorithmX2** [comment] 2017-06-20 19:34
@RepoDraghon how about you?
@kirokadura or you?

Do either of you have an older version of the CTM mod? Or if not can you isolate another mod with it?

**Comment by RepoDraghon** [comment] 2017-06-24 04:36
seems to be fixed with current mod updates... everything is back to normal... still using 12.12 will try 12.14 later... seems it definitely was another mod that must have just updated... as to which, I'm sorry, no clue what one... I did disable Hwyla by TehNut... might start there? but it's just a hook for WAILA by ProfMobius

Update: 12.14 is good now... I doubt it's an Optifine issue... however, I do notice a drop in FPS

**Comment by AlgorithmX2** [comment] 2017-06-30 23:42
I guess that means this is resolved then? Something else updated and the issue went away, so I guess I'll count that as a win, and seems it wasn't optifine after all.

**Closed as completed by AlgorithmX2** 2017-06-30 23:42 UTC
Labels: Invalid
