### ISSUE TITLE
Can't place items

### ISSUE THREAD

**Issue by Dlhmach** [ChiselsAndBits/Chisels-and-Bits#265] opened 2017-05-05 07:13 UTC
I was a little annoyed to find I couldn't place some objects on a chiseled block even if I left the entire top face untouched.
I was trying to place a flowerpot on a table.
MC version 1.11.2
C&B version 13.10
I do not have optifine but it's not relevant to the issue.

I'd just like to know if that's supposed to work or not, since I like putting flowers on the kitchen table, etc. Is this a MC Multipart thing? They haven't updated for 1.11.2 yet, so I don't have it.
Thanks
Sarah

For any bug reports please provide the following,

* MC Version:
* C&B Version:
* Do You have Optifine:

**Comment by AlgorithmX2** [comment] 2017-05-05 15:16
This is a duplicate of https://github.com/AlgorithmX2/Chisels-and-Bits/issues/254

This is because many MC Blocks are checking to see if the block is opaque, rather then having a solid top.

**Closed as completed by AlgorithmX2** 2017-05-05 15:16 UTC
Labels: Duplicate
