### ISSUE TITLE
Water render issues

### ISSUE THREAD

**Issue by Nathamn** [ChiselsAndBits/Chisels-and-Bits#1034] opened 2022-12-06 16:35 UTC
I've been playing in a server hosted by a friend and I noticed a small render issue where the water disappears depending on the direction you look at. Thought it could be something else messing with rendering but it only started happening in this current are when I made some stuff with C&B.

This doesn't happen to the friend that hosts the server.

* MC Version: 1.16.5 forge 36.2.39
* C&B Version: 1.0.43
* Do You have Optifine: Yes.

![2022-12-06_18 32 44](https://user-images.githubusercontent.com/119959769/205969128-911cbbdd-7d2d-4320-b097-f9cce8950309.png)

![2022-12-06_18 32 45](https://user-images.githubusercontent.com/119959769/205969112-7b757e38-2c92-4934-91f1-bed53733a956.png)

**Comment by marchermans** [comment] 2022-12-06 16:51
I am not sure what I am supposed to see here.

**Comment by Nathamn** [comment] 2022-12-06 17:04
To be honest, I'm unsure myself. The screenshots are from the same river, and they show how look direction makes water disappear.

It has something to do with C&B so I figured this would be the best place to go about this

**Comment by marchermans** [comment] 2023-01-20 18:13
I was not able to reproduce this.
I am going to close this as you are the only one that reported this, I am unable to fix this issue.,

**Closed as completed by marchermans** 2023-01-20 18:13 UTC

**Comment by YippyCorgis** [comment] 2024-04-18 14:12
Also experiencing the same issue on 1.12.2. Happens for any "fluid" material; vanilla or modded. Confirmed to be C&B by removing from mod list.
