### ISSUE TITLE
constant crashing issues followed by being unable to place/destroy bits

### ISSUE THREAD

**Issue by kartoffelsaretasty** [ChiselsAndBits/Chisels-and-Bits#743] opened 2021-10-03 19:04 UTC
we updated our enigmatica 6 0.5.14 server from chisels & bits version 1.0.5 to 1.0.11

now whenever someone plays around with bits they just crash, it's hard to pinpoint, at this point i started crashing as soon as i log onto the server (presumably because i'm stuck into a phantom block after removing bits)

this is my crash log

https://paste.ee/p/hGoOK

**Comment by marchermans** [comment] 2021-10-03 19:56
Hello thanks for the report.
Currently this looks like an incompatibility with TOP.

Seems like the targeting algorithm that they use provides a weird value to C&Bs bit targeting processor.

I will see what I can do to fix this.

**Comment by marchermans** [comment] 2021-10-03 20:59
Reproduced will publish a fix tomorrow

**Comment by marchermans** [comment] 2021-10-04 12:04
Fixed in 1.0.12 and 1.1.6 respectively.

**Closed as completed by marchermans** 2021-10-04 12:04 UTC
