### ISSUE TITLE
While trying to load the mod, the launcher crashes

### ISSUE THREAD

**Issue by thecakeslayer** [ChiselsAndBits/Chisels-and-Bits#295] opened 2017-08-04 20:25 UTC
As the title states, when I try to load C&B the launcher crashes with a severe error message stating that it is from the mod itself. Im not sure how to go about getting this resolved. 

For any bug reports please provide the following,

* MC Version: 1.12
* C&B Version: 1.12
* Do You have Optifine: no

**Comment by AlgorithmX2** [comment] 2017-08-04 20:27
You'll need to give me some of those messages, or screenshots, or logs. I need something to work with.

**Comment by thecakeslayer** [comment] 2017-08-04 20:30
"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Chisels & Bits (chiselsandbits)" 

This is all I can give you. I can't seem to be able to access the crash logs

**Comment by AlgorithmX2** [comment] 2017-08-04 20:33
That just says that an exception was thrown, and doesn't tell me what the exception was. Unfortunately this is like stating that the sky is blue, gives us the knowledge that something happened, but not remotely what.

if your launcher isn't giving you access to other logs perhaps trying a different launcher would help. I usually use vanilla launcher, and I don't have any issues starting the game, or getting the crash logs.

**Comment by thecakeslayer** [comment] 2017-08-04 20:36
I am using the Vanilla launcher, its strange that I'm not able to launch the game or access the logs.

**Comment by AlgorithmX2** [comment] 2017-08-04 20:37
The logs folders should be available in the same folder that contains mods folder, should be marked as logs or something else. I can't imagine why you wouldn't be able to access them.

**Comment by thecakeslayer** [comment] 2017-08-04 20:41
I was looking at a completely different location. Here is the last log I have 
[2017-08-04-1.log.gz](https://github.com/AlgorithmX2/Chisels-and-Bits/files/1201576/2017-08-04-1.log.gz)

**Comment by AlgorithmX2** [comment] 2017-08-04 21:32
That file only contains,
[12:42:10] [main/INFO]: Setting user: linksys1221
[12:42:15] [main/INFO]: LWJGL Version: 2.9.4
 
maybe clear them out, then  re-run the launcher. and upload all the files? Or look though the logs for the error before uploading them.

**Comment by Insanimous** [comment] 2017-08-05 16:29
I was having the same problem with the mod where it would crash whilst trying to load the game. I found where it showed a loading error, but I don't understand any of it. Maybe you could have a look at it.

[12:18:39] [main/ERROR] [FML/]: The following problems were captured during this phase
[12:18:39] [main/ERROR] [FML/]: Caught exception from Chisels & Bits (chiselsandbits)
java.lang.NoClassDefFoundError: net/minecraftforge/registries/IForgeRegistryEntry
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:546) ~[forge-1.12-14.21.0.2333.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252) ~[forge-1.12-14.21.0.2333.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230) ~[forge-1.12-14.21.0.2333.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:583) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:233) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466) [bhz.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bhz.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.registries.IForgeRegistryEntry
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	... 39 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	... 39 more
[12:18:40] [main/INFO] [STDOUT/]: [net.minecraft.init.Bootstrap:func_179870_a:552]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 8/5/17 12:18 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Chisels & Bits (chiselsandbits)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/registries/IForgeRegistryEntry

**Comment by AlgorithmX2** [comment] 2017-08-05 19:12
@Insanimous You've removed the part of the log with versions, but because net/minecraftforge/registries/IForgeRegistryEntry is missing, I assume your using a old alpha/beta version of forge for 1.12.

C&B Requires at least the first recommended version, most of the logic related to registration was re-written for that release.

**Comment by Insanimous** [comment] 2017-08-05 19:35
Thanks, it fixed it. I had installed an older version of Forge before for it to be compatible with Optifine, but I deleted Optifine and got the recommended Forge version and it runs fine now. Thank you!

**Comment by AlgorithmX2** [comment] 2017-08-07 20:49
@thecakeslayer Any news on this on your end? Is your problem the same?

**Comment by thecakeslayer** [comment] 2017-08-07 20:58
I had issues launching with optifine installed so I just needed to reinstall forge. I should have done this first before coming here.  Whoops.

**Comment by AlgorithmX2** [comment] 2017-08-07 20:59
So I suppose that means no more issues? All clear?

**Closed as completed** 2017-08-07 21:11 UTC
Labels: Invalid

**Comment by BlackKayo96** [comment] 2022-06-09 17:34
I have a similar problem but when I tried updating to the newest recommended version of forge it didn't fix it what would you need to see to try to identify the problem
