### ISSUE TITLE
Vanilla grass bits are grey

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#256] opened 2017-04-01 07:32 UTC
![2017-04-01_09 30 00](https://cloud.githubusercontent.com/assets/25916106/24576555/fed228c6-16bd-11e7-8123-b6200bad94ab.png)

**Comment by Phylogeny** [comment] 2017-04-01 10:04
You have not included the required information for issues. Click 'New issue', then copy-paste and answer the required questions here.

**Comment by ghost** [comment] 2017-04-01 13:39
**Minecraft version**: 1.10.2.
**Chisels & Bits version**: 12.12 (latest for 1.10.2)

Yes, I do have OptiFine (D7; latest) installed.

**Comment by AlgorithmX2** [comment] 2017-04-01 20:06
@PapiDimmi what is the pipe like object in the screen shot? are you using this in conjunction with MCMP? If so MCMP doesn't support this feature, please confirm.

**Comment by Phylogeny** [comment] 2017-04-01 21:36
@PapiDimmi There is a reason why the information is requested from everyone that opens issues. It's quick, easy, helpful, and not at all unreasonable to request. I'm curious as to the reason you resent the messenger for simply informing you that you should provide it.

**Comment by ghost** [comment] 2017-04-01 21:56
>what is the pipe like object in the screen shot? are you using this in conjunction with MCMP? If so MCMP doesn't support this feature, please confirm.

@AlgorithmX2 It’s the cable from Refined Storage. I just tested in a creative world, and this only happens when the cable is in the middle of a block.

![2017-04-01_23 54 36](https://cloud.githubusercontent.com/assets/25916106/24582741/99e2c618-1736-11e7-83ac-14b957066d72.png)

Is this a bug on Refined Storage’s part or on Chisels & Bits’ part?

>There is a reason why the information is requested from everyone that opens issues. It's quick, easy, helpful, and not at all unreasonable to request. I'm curious as to the reason you resent the messenger for simply informing you that you should provide it.

@Phylogeny I always include that information in my issues, but I forgot it this time. It was merely a mistake.

I’m not sure what you mean by “resent the messenger.” If you’re asking me why I gave you a thumbs down emoji, that was a mistake. I meant to give you a thumbs up emoji.

**Comment by Phylogeny** [comment] 2017-04-01 21:59
@PapiDimmi Thanks for the response. Yes, that is what I meant. Curiosity satiated. :)

**Comment by AlgorithmX2** [comment] 2017-04-01 22:18
This isn't a bug with either refined storage, or with C&B, its simply because MCMP which is used to share the same block space doesn't support the coloration of parts 

Which makes this a duplicate of https://github.com/AlgorithmX2/Chisels-and-Bits/issues/122

**Closed as completed by AlgorithmX2** 2017-04-01 22:18 UTC
Labels: Duplicate
