### ISSUE TITLE
Chiseld blocks turned into ghost blocks you cannot remove

### ISSUE THREAD

**Issue by Underground0live** [ChiselsAndBits/Chisels-and-Bits#312] opened 2017-10-07 00:36 UTC
After trying to chisel on an cable, the Game crashed. After reloading, many chiseld blocks changed into "ghost blocks". It is glitches when walking over it. You cannot destroy these blocks, and you cannot place a normal block at this place. But a chiseld block. When you replace the ghost blocks with chiseld blocks, they come back after reloading the world.

* MC Version:1.12.2
* C&B Version:14.8
* Do You have Optifine: Yes

**Comment by Underground0live** [comment] 2017-10-07 00:38
* A cable from Refined Storage

**Comment by AlgorithmX2** [comment] 2017-10-07 01:11
I would suggest updating MCMP to the build that came out a few hours ago, I was not able to reproduce this issue.

**Comment by AlgorithmX2** [comment] 2017-10-13 21:34
I'm thinking this is also a duplicate of #310 but a slightly different result. Closing since I can neither reproduce the issue mentioned and believe it to be tied to the MCMP Issue.

**Closed as completed by AlgorithmX2** 2017-10-13 21:34 UTC
Labels: Third Party Issue
