### ISSUE TITLE
Suggestion: Bigger Designs

### ISSUE THREAD

**Issue by p4di** [ChiselsAndBits/Chisels-and-Bits#381] opened 2018-04-19 20:41 UTC
would be great if there was a way to easily replicate bigger designs. 
Example: I recently built a spherical Gas Tank (5x5x5 blocks) for my Mekanism Plant and I'll copy that tank quite a few times for the build. While Chisel Designs work fine, it takes quite a while to rebuild the structure again. Having the possibility to do it with just one design would be awesome!

**Comment by AlgorithmX2** [comment] 2018-04-19 20:42
Duplicate of #337

**Closed as completed by AlgorithmX2** 2018-04-19 20:42 UTC
Labels: Duplicate
