### ISSUE TITLE
Few ones for you here

### ISSUE THREAD

**Issue by DestinedToSuffer** [ChiselsAndBits/Chisels-and-Bits#750] opened 2021-10-05 23:09 UTC
* MC Version: 1.17.1
* C&B Version: 1.1.6
* Do You have Optifine: No

This is run on a forge server with about 100 mods mostly around the idea of extending vanilla gameplay.

- Chisel blocks become dark and lighting does seem to work properly
- Modification table is missing a texture on the left side
- All tables/workbenches related to C&B do not break faster with a specific tool nor do they drop anything apon breaking (assuming these are not intentional)
- No audio on picking up chiseled bits off the ground
- Lastly the biggest one... on servers it seems C&B randomly decides to just stop working, you cant chisel blocks nor place them. The only fix being a server restart at this time. (sidenote: checked the logs and not a single thing from chisel and bits besides the loading at server start)

**Comment by marchermans** [comment] 2021-10-06 17:34
@DestinedToSuffer I was largely able to verify and reproduce the issue.
Except the modification table missing a texture on the left side....

![image](https://user-images.githubusercontent.com/5585406/136254656-aaf3fba6-b6fb-4042-b06d-3a29cdc70eaf.png)

**Comment by marchermans** [comment] 2021-10-06 17:53
Besides that I can not reproduce the "dark" blocks.

There is another issue open #749 but even with those screenshots and me remodelling those I was not able to reproduce that. So could you again create some screenshot of your graphics/video settings and check if you have the forge lighting pipeline enabled?

Thanks

**Comment by marchermans** [comment] 2021-10-13 11:02
Fixed in the newest release.

**Closed as completed by marchermans** 2021-10-13 11:02 UTC
