### ISSUE TITLE
Crash when start

### ISSUE THREAD

**Issue by ahfuba** [ChiselsAndBits/Chisels-and-Bits#673] opened 2021-05-13 15:13 UTC
* MC Version: 1.16.5
* C&B Version: Latest at the Curse (0.3.4)
* Do You have Optifine: No

When I try to start my game, it gives the same error at same time. 
Thats the list of the mods I have:
XLFoodMod
WorldEdit
HorseCarts Mod
(my own mod that only a jar file, does not have an library file)
Create

And thats the crash log:
```
Description: Rendering overlay

net.minecraftforge.fml.ModLoadingException: Chisels & bits (chiselsandbits) encountered an error during the sided_setup event phase
§7net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: chiselsandbits:icons/sıngle
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:124) ~[forge:36.1] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$34(ModLoader.java:326) ~[forge:?] {re:classloading}
	at java.util.HashMap.forEach(Unknown Source) ~[?:1.8.0_291] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:229) ~[forge:?] `{re:classloading}`
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:326) ~[forge:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:165) ~[forge:?] {re:classloading}
	at net.minecraft.client.renderer.texture.AtlasTexture.func_229220_a_(AtlasTexture.java:96) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.model.ModelBakery.processLoading(ModelBakery.java:213) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.model.ModelLoader.<init>(ModelLoader.java:72) ~[forge:?] {re:classloading}
	at net.minecraft.client.renderer.model.ModelManager.func_212854_a_(ModelManager.java:57) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.model.ModelManager.func_212854_a_(ModelManager.java:20) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11) ~[?:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_291] {}
Caused by: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: chiselsandbits:icons/sıngle
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[?:?] {re:classloading}
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:42) ~[?:?] {re:classloading}
	at mod.chiselsandbits.core.ChiselsAndBitsClient.registerIconTextures(ChiselsAndBitsClient.java:85) ~[chiselsandbits:?] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:36.1] {re:classloading}
	... 17 more

```

**Comment by marchermans** [comment] 2021-05-16 11:42
I can't reproduce this.

**Comment by marchermans** [comment] 2021-08-20 18:15
Should be fixed in the newest beta.

**Closed as completed by marchermans** 2021-08-20 18:15 UTC
