### ISSUE TITLE
Bits place in the wrong location

### ISSUE THREAD

**Issue by treeco123** [ChiselsAndBits/Chisels-and-Bits#559] opened 2020-12-19 16:15 UTC
C&B version 0.2.8 for MC 1.16.4, forge 35.1.13, no other mods installed
Platform: Manjaro Linux w/ KDE Plasma

This screenshot shows an attempt to place bits randomly on different sides of a block: https://i.imgur.com/16HNbfb.png

When placed on east or west sides, bits place offset 16 units from where clicked.

When placed north or south, bits place on the far side clockwise from where clicked, and offset one unit outwards

When placed on the top or bottom, bits place offset one unit upwards/downwards.

Chiselling seems to work fine, it's just placing Bits from the inventory. Thanks for the work on the mod.

**Comment by Baa14453** [comment] 2020-12-21 00:56
Duplicate of https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/549

**Closed as completed** 2021-01-10 14:58 UTC
Labels: Bug, Duplicate
