### ISSUE TITLE
Chiselled water causes server OOM

### ISSUE THREAD

**Issue by LixieWulf** [ChiselsAndBits/Chisels-and-Bits#890] opened 2022-03-12 02:55 UTC
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

When I attempt to chisel water via right-clicking a water bucket into a chiselled block, it causes an out of memory error on our SMP server.
[literally just a single line, no stacktrace](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/8236904/crash-2022-03-11_04.54.12-server.txt)
I do not know the cause - all I did was remove a slab sized and volume area directly in the middle of a block, then right-clicked with a bucket while attempting waterlogging tests.
I do not know if this has been fixed either as of right now.

For any bug reports please provide the following details as well,
* MC Version: 1.18.1
* C&B Version: ChiselsBits-forge-1.18.1-1.2.81
* Do You have Optifine: no lmao

**Comment by marchermans** [comment] 2022-03-21 10:48
Interesting I don't know what the cause of this is.
I for sure can't reproduce this though. How much memory did you assign the server?

**Comment by LixieWulf** [comment] 2022-03-21 15:05
I think the server has 16 gigabytes of RAM to use. I should also mention - the error is not just an out of memory, it entirely softlocks the server. No players can join and the player list is not updated in the server selection menu. Joining results in "Timed out".

**Comment by marchermans** [comment] 2022-03-22 07:07
Interesting I was not able to reproduce this, but I will see what I can do.

**Comment by LixieWulf** [comment] 2022-03-23 21:08
Sounds good
Sorry for late reply, I rarely use GitHub at this moment and my notifications are broken.

**Comment by Eleiyas** [comment] 2022-04-18 23:09
MC 1.18.2
Forge: 40.0.54
C&B: 1.2.84-universal (Forge)

Can confirm this same issue is happening here. 
Someone chiseled a waterfall next to his base, which crashed the server, then upon either of us loading in, after the server auto-reboots, the server crashes with "return code 137" on Multicraft, which is "Server OOM". 
Server works fine upon removing the C&B mod.

**Comment by marchermans** [comment] 2022-04-19 03:48
Please entry to reproduce this with vanilla c and b

Cause i was not able to.
Also there are options in the config to reduce the cache sizes you can try those.

**Comment by marchermans** [comment] 2022-06-24 20:29
Fixed in 1.2.100

**Closed as completed by marchermans** 2022-06-24 20:29 UTC
Labels: Bug, Requires Research, Waiting On Response, Priority: Medium
