### ISSUE TITLE
Game crashing/collision breaking when walking on chiseled vanilla blocks

### ISSUE THREAD

**Issue by MEATYTHINGS** [ChiselsAndBits/Chisels-and-Bits#816] opened 2022-01-03 20:00 UTC
I have begun to experience an issue when using your (awesome) mod that seems to break collision or outright crash the game while on a server with repeatable results. When walking over or dropping onto a bit or chiseled block, sometimes the player will become stuck on top of the block and unable to move. For instance, if I chisel a single bit from the top of a stone block and stand on it, I will become stuck roughly half the time. There are no blocks above the offending block, so there should logically be no collision errors. Breaking the offending block does not seem to solve the problem, as the player will remain stuck in the air. The same error does not seem to occur in singleplayer, and the server does not crash with the game client.  Sometimes it will crash the game immediately, with the error:  
The game crashed whilst ticking entity
Error: java.lang.IllegalArgumentException: Start element (9223367638808264704) is larger than end element (-9223372036854775808)
Exit Code: -1
[crash-2022-01-03_11.47.40-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7803544/crash-2022-01-03_11.47.40-client.txt)

It should be noted I am using Flywheel and Create, both updated to the latest version. I am using other mods, but none that should interact with collision, physics or block properties other than Flywheel and Create. Thank you for all your hard work and the amazing mod you've put together!

For any bug reports please provide the following details as well,
* MC Version: 1.18.1
* C&B Version: 1.2.62
* Do You have Optifine: Yes, 1.18.1 HD_U_H5_pre4

**Comment by marchermans** [comment] 2022-01-04 06:22
The crash is related to optifine, I have seen instance where a player can get stuck in a C&B block, but was not able to reproduce this.

If you can get me a reproduction case which I can reliably reproduce I am more then happy to take a look at it.

**Comment by MEATYTHINGS** [comment] 2022-01-05 01:02
Thank you for the quick reply! You're right on the optifine front, it seems to not crash at all when optifine is uninstalled. The condition that seems to get me stuck is usually related to falling on the C&B block it seems, the specific portion of my world where it seems to happen the most is on a C&B block next to a chest and some vines. If I jump off the chest or drop down from flying in creative I can sometimes get stuck on the C&B block closest to the chest. Sometimes adding or removing a single bit of a block and standing on it also gets me stuck, but this has been unreliable to reproduce and is easily solved by breaking the c&b block before reconnecting to the server. I haven't experienced anything game breaking now that I know optifine is causing the crashes, all the collision errors seem to be solved by breaking the offending block and reconnecting to the server. Thank you again for the quick reply and all your hard work on this amazing mod!

**Comment by marchermans** [comment] 2022-01-07 12:19
Closed in #825 released in 1.2.65

**Closed as completed by marchermans** 2022-01-07 12:19 UTC
