### ISSUE TITLE
Water renders brown

### ISSUE THREAD

**Issue by AleFunky** [ChiselsAndBits/Chisels-and-Bits#865] opened 2022-02-05 18:50 UTC
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

literally what title says
![imagen](https://user-images.githubusercontent.com/55950650/152654894-003b3e7e-e198-4ecb-be74-c637c787532d.png)

For any bug reports please provide the following details as well,
* MC Version: 1.18.1
* C&B Version: 1.2.79
* Do You have Optifine: no

**Comment by marchermans** [comment] 2022-02-05 19:19
Does normal water render brown in that biome

**Comment by AleFunky** [comment] 2022-02-06 08:35
nope, water in that biome render blue, is a forest the biome

**Comment by AleFunky** [comment] 2022-02-06 14:43
![imagen](https://user-images.githubusercontent.com/55950650/152686200-35682012-4591-4827-b3aa-eadc194adb90.png)

**Comment by marchermans** [comment] 2022-02-06 16:11
Weird. I have never seen that one.
Will do some research

**Comment by marchermans** [comment] 2022-02-07 18:45
Not reproducable to me:
![image](https://user-images.githubusercontent.com/5585406/152851716-39208598-dd48-47db-91d0-f0beea75e759.png)

**Comment by marchermans** [comment] 2022-02-07 18:45
But I might have an idea what the cause is.

**Comment by netcore10** [comment] 2022-05-01 14:50
Can confirm, happens to me too

**Comment by marchermans** [comment] 2022-06-24 20:29
Fixed in 1.2.100

**Closed as completed by marchermans** 2022-06-24 20:29 UTC
