### ISSUE TITLE
Ghost blocks left behind after deleting bits

### ISSUE THREAD

**Issue by LindaJuffermans** [ChiselsAndBits/Chisels-and-Bits#760] opened 2021-10-13 09:15 UTC
MC Version: 1.16.5
C&B Version: chiselsandbits-1.0.12-RELEASE-universal.jar
Do You have Optifine: No

Place bits:
![2021-10-13_11 13 22](https://user-images.githubusercontent.com/31929183/137104094-f68fab8a-c4ae-4d06-97bb-1032780bceaf.png)

Delete all:
![2021-10-13_11 13 34](https://user-images.githubusercontent.com/31929183/137104138-42442a30-963d-4d31-ae89-5f4a25f6b034.png)
![2021-10-13_11 13 39](https://user-images.githubusercontent.com/31929183/137104145-38ede5b1-feb9-46cb-967f-02c107a42bf8.png)

See a ghost block (waila) staying behind:
![2021-10-13_11 13 42](https://user-images.githubusercontent.com/31929183/137104181-14742726-39ec-479f-9a0f-06c55f5a1a4d.png)

The ghost block can only be removed in creative mode.

**Comment by marchermans** [comment] 2021-10-13 09:33
I will do some research as to what the cause could be here.
Obviously this is not correct.

**Comment by LindaJuffermans** [comment] 2021-10-13 09:34
Workaround: Without going into creative mode, I can place another block (e.g. cobblestone) in the same spot and then break that.

**Comment by marchermans** [comment] 2021-10-13 11:15
Besides this I also checked in into the Radial menu scaling stuff.
With regards to this I am not sure what I can do.

Mojang has implement the GUI scale as a hard scaling option, which I have no real control over......

**Comment by marchermans** [comment] 2022-01-07 12:20
Closed in #825 released in 1.2.65

**Closed as completed by marchermans** 2022-01-07 12:20 UTC
Labels: Bug, Requires Research, Priority: High
