### ISSUE TITLE
when breaking bits game would randomly crash

### ISSUE THREAD

**Issue by ZoruaBit** [ChiselsAndBits/Chisels-and-Bits#581] opened 2021-01-15 09:46 UTC
The game crashed whilst tesselating block in world
Error: java.lang.NullPointerException: Tesselating block in world
Exit Code: -1
https://pastebin.com/EAzgjTNc 

For any bug reports please provide the following details as well,
* MC Version:1.16.4
* C&B Version:latest (0.2.9 release
* Do You have Optifine:yes

**Comment by marchermans** [comment] 2021-01-15 15:58
Duplicate of: #577

**Closed as completed by marchermans** 2021-01-15 15:58 UTC
Labels: Bug, Duplicate, Priority: High
